apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zot-tls
spec:
  dnsNames:
    - registry.kvlk.hu
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: zot-tls
  usages:
    - digital signature
    - key encipherment
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: zot-tls
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: envoy-gateway-system
  to:
    - group: ""
      kind: Secret
