apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zot
resources:
  - secrets.yml
  - zot.yaml
  - route.yml
  - certificate.yml

configMapGenerator:
  - name: zot-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
