---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zot
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: zot
  hostnames:
    - "registry.kvlk.hu"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: zot
          port: 5000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Referrer-Policy
                value: "no-referrer, strict-origin-when-cross-origin"
              - name: Strict-Transport-Security
                value: "max-age=63072000; includeSubDomains"
              - name: X-Content-Type-Options
                value: "nosniff"
              - name: X-Frame-Options
                value: "SAMEORIGIN"
              - name: X-XSS-Protection
                value: "1; mode=block"
              - name: Permissions-Policy
                value: "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"
