---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: local-user
  namespace: zot
spec:
  encryptedData:
    pw: AgA3gUBcErJpsf5oPdHOocbdKKZIwxSw0hbcgCIuBx56X2cSnej5PjO5W495IsfCdAh3qkz5ggwKS87IcOENxKYtXE2M8wloKLQg1iYhtve6RMCmRm0xy+pA8tgUu8E1F5nqhDTxb5WH1XBj1cOLdyV25mMnTEQjfPca4myZI9qWwlYJDmXFVt3pefRs9bFC2rJ+/0bx6REO+eeQi1tBcPGg4j2GIdMElwjYPrSoOveeQCbpLeIxZFuv+CcEozyogGFb4rGT7d2aGAPviIQYZWYQxnvxBlVVDA3ie4qiHaIJdovPWXqfW3k/vz+pleXr03/thWcnqlBxQsghKaOlzAeyIBzlUGJb5q9VelG1aewpJdMNWMrmGgFotyP8Zu6OGhiwNAWmJ03uHLmMECtXn4RLRlckC1OZw6H2gVr4LJuYv62om1LD4ROb4xrvOAGXChV3NcFqC52hRi+Z3ML7fMXFG+S4AMfHopX7MMmNAXGe30/poz4RUIpocvwxwWoDEKOGwkcbsDtxjAJwvIiGraKHGEOp3j26USWa+UKuWbdcFpfiBeN1TBazTZBvrEiZZByChXZJMbSfz6DmGbOPvtEVDWoFfaKaB6W7NahxKZUQW8Vn8TrRvSCH1S+IP3vbtWXuuqrbECIrhzxobifr7NvymUq6zrOWLXNzYnfDu9/6AFVp99ndscdAFlY88mV9gVmWIk3iUPrHsSPJlZx7TOm4SjYZpuKojmErTfu5n/uTkcjFJUBFai//HpHb3dG6I40rFw8g4DunLp4WpoH7zukbP7xu
  template:
    metadata:
      creationTimestamp: null
      name: local-user
      namespace: zot
    type: Opaque
