---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd
  namespace: zot
spec:
  encryptedData:
    htpasswd: AgBR0qAQXHuf5e0y2WuQkws0uG8bGfoFAFZ6iekkF1LHzZiUQFRvqGLzfQ4Rl3zNRovq7JGtRCosLBt3hDO4qy2qpDFVb4RkLgjZlciJq77wGh/TTEkYhI10QG4BdBZ1T+5bYFfuyqUnrnHZWZ0Imnw0WyuLgIk4/PsJD6S4ORP0o93EiCM3WYemJgS7Y9TsAtieb4c1GR+YnV7CYDPkvUlMDnhjoPszyet6XUf79O8CUczBZchETz28smBTJDBSBixXJojgUwDSuqPLXs31x8/iKt5YLLUSBCvlUFS66tGoUYnCG9sTVlEpxN/JiSmKOPwbmkSEEc8CEaNFDTx4b8f38IRGxfEe2OipDtjfQT3G5q1KZnTMLGbH2/0FOdYOR7rnyIwBx+yvslrkmGlZOvOR3bFsuVqqMe48bAFaPLGVVRF5sDfflAgZ3WqFP5WfDCRzS5T3iSL3JlkbYLe6Wb/GBq2A2BrwFuLUARsbM2Ho17TAb5JxQOfsFnR1sMMAPAcn0Yv8w28AnPH64jdYoK9vom6uTeUnAzmpvhvgLQLRrcWox2h3/XGicAMY7vpnbGrcRPHnro6S5vg0L3VxmslisDVOeiZRluJcroqceo5/xsw/rrJVM8bnXIOIGh8BNqFBulL0HSyliqIcv4EqSYvd/hjFt3pHMMjqZpOQOdMvj7enY46Zcs92cxUiom+Y89wapIfXGPxFzv0cB715Fnbnkm2itDYktBn/dBUyBIdQbC0gdR8JcffMy581/onr7Ffk1tbdtmKJY25+dszjtby9OEU=
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd
      namespace: zot
    type: Opaque
