apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zot
  namespace: zot
spec:
  interval: 10m
  targetNamespace: zot
  releaseName: zot
  chart:
    spec:
      chart: zot
      version: "0.1.95"
      sourceRef:
        kind: HelmRepository
        name: zot
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: zot-values
