apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: harbor
spec:
  interval: 10m
  targetNamespace: harbor
  releaseName: dragonfly
  chart:
    spec:
      chart: dragonfly
      version: "v1.35.1"
      sourceRef:
        kind: HelmRepository
        name: dragonfly
        namespace: flux-system
