apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 10m
  targetNamespace: harbor
  releaseName: harbor
  chart:
    spec:
      chart: harbor
      version: "1.18.1"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: harbor-values
