apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - secrets.yaml
  - dragonfly.yaml
  # - harbor.yaml
  - networkpolicy.yaml

configMapGenerator:
  - name: harbor-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
