---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: harbor
spec:
  encryptedData:
    password: AgCD2DdYuAsFrnlrqjYw6OTCSFvUcGUGCyth9xQq09oN+GbYM+NWsODpH3UvYdJY+dPfGHeFojvxeGZZI5oND0KjU2UcGgTBbtBFFekb6mG92bqZbifIM3W6LLpHGuMmVYtoDZ0SvYqbC1d2LXkI/MtK98E1Fb24oEXnGirAFC4aAgXj18ASbLoy01bGUnpXCVEu97Wcob6hUjXnnXVsb9LYgZ8R8+CjV3SCAwvL57y5upzPaZJfqMPBE1g5OMI8oJ92go2B9/gg6ISePpfmxpkfKbw7902z5P6fS9Ko4oxHsyzDblwuC3MvK6SU3FGJ4RIKr8eoDzxhErkldUIeHcZIp0om4ehDcDfL3DPcX6iA+vRuGasOnKIPHHYkRKFUvIVJy7NqOr1/kUiJ3tJ+VQtvkbPmQueHEso7GSv6UZNy3xMR5jdwNuOeIQxgoh4fGdA1BAL8ZPitMNsCyq8VaETXscsgfcdUkBidyPwVb2span5cX4rtXJ6yy+2vk5QWnk8cpDnjSMhnKHsjcu064rXldx6qSfMMl74taPTL4IK3jhiUCZVtcqZq+eCeeMwyfHYGPxlVMqF8zFkSqnWmKXFB44lH22ytNIXQr2QDFhUM4l3zM2Rn0qPY/WAh6WBZOdVxtKaKJ+iwkZdOjD+caEsaown5AQOQyMnO6v3drIvfjTD8EIqjVvbtPgBS5wSVSxrewr8xO5xsvWa9BSyLmvXp1C29IQ==
    username: AgAIX5v+k2PNG3IQ5CiveOzOSIxu6q/qXXx4qOALJgWjhz5scrgRp1wKZFLtywWmEeb4NaLucp323oZmH8wuFbXs6D5+b5rMJb2V+D7qezfEoulgGsdPLMx8J38ONgAT+YAlxuTBrvea7UhVssroyRjhXLKttX2iHcpe9aSjkj5N/6uTU46OwRl2axhszq7UR5odC45YHHJnR0O9K97SkpOjvOjPLODedWtFspa7AfI6pHC4phcEz8+MHuXPEHSLi8BtMr0ljP9ZnRFLi4ZMvvmVcat8+57if4b38fe9SKiskXJrw32Aho9kHVpDNgXyI5lEcn8qTOQ90OAkNJvUKzNMdJgVOCXx8mIaKZsM2l5GrkfycpAxes5kozB18tMDRwcdOcqVuSiqHYsYUrSNKMgJe9oOodubl8oaXbWIybn5OUMIdDbQODbAX9yOVp6S+eXlkvWddPI0aYh36ezEMQYysWcTpRgUSYCk89Hm6SRPqGQQnCxw7h+WNDZ0T4a4TD/7mYY25I0RNB7oQYNgF42VgERScS/WkBqhV0k9OJs5Qn5HpthZvP5lO88r24Yc0HQNgIhbzOY9BgRkDmL+bfinV92yW8Q+veR0cfpeM+CEgBNUc92FPtifdRQmCjXgQrFVShcTaEzlADUmJDYfmtGLkpjmXVPhR3GZkaw1J2iLLIunTXvKn3p8hNKMkkNH03LGD2XkcPw=
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: harbor
