database:
  type: external
  external:
    host: pooler.postgresql.svc
    username: harbor
    databaseName: harbor
    coreDatabase: harbor
    clairDatabase: harbor-clair
    notaryServerDatabase: "harbor-notary-server"
    notarySignerDatabase: "harbor-notary-signer"
    existingSecret: db-secret
    sslmode: "require"

expose:
  tls:
    enabled: false
    certSource: none
  type: route
  route:
    parentRefs:
      - name: eg
        namespace: envoy-gateway-system
        sectionName: harbor
    hosts:
      - harbor.kvlk.hu

updateStrategy:
  type: Recreate

externalURL: https://harbor.kvlk.hu

notary:
  enabled: false

clair:
  enabled: false

redis:
  type: external
  external:
    addr: harbor-dragonfly

portal:
  image:
    repository: docker.io/tojgli/goharbor/harbor-portal
    tag: dev

core:
  image:
    repository: docker.io/tojgli/goharbor/harbor-core
    tag: dev

jobservice:
  image:
    repository: docker.io/tojgli/goharbor/harbor-jobservice
    tag: dev

registry:
  registry:
    image:
      repository: docker.io/tojgli/goharbor/registry-photon
      tag: dev
  controller:
    image:
      repository: docker.io/tojgli/goharbor/harbor-registryctl
      tag: dev

trivy:
  image:
    repository: docker.io/tojgli/goharbor/trivy-adapter-photon
    tag: dev

exporter:
  image:
    repository: docker.io/tojgli/goharbor/harbor-exporter
    tag: dev
