apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentbit
  namespace: fluentbit
spec:
  interval: 10m
  targetNamespace: fluentbit
  releaseName: fluentbit
  chart:
    spec:
      chart: fluent-bit
      version: "0.54.1"
      sourceRef:
        kind: HelmRepository
        name: fluentbit
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: fluentbit-values
