apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluentbit
resources:
  - secrets.yaml
  - fluentbit.yaml

configMapGenerator:
  - name: fluentbit-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
