---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-credentials
  namespace: fluentbit
spec:
  encryptedData:
    PASSWORD: AgA7z4HoMs+ps5Tn6qIqqk79rcUCY7ZuJBmTeKuemxwVnHFzJb492jep5BKKYSctiOLfhze6BtnqfOnB0p6kUoTCislXwtizg9oqO342FGwGd7KQVXqQ1Z5Pvg1kS2FB3KlJhcN4kaxYvBGmoWgbv90XcOXYhu+Arljs+GlDzAtxVjN7lPciOYm2ivbAl085IbyivVM3xyc/9oNLGZQ07DsEArc8PBC3W62Wz1k3B7gyTfI2QpPBTtbq8QBPnqicQmqE3jfeKwVyKqPLNeawRBQ1Iv6BIJcTOP2djnl2pLhx7teBhL47ziOC6zWU7chwR4qq/1wO+hlC24YE2xgNIoOiyvrXxfnl+gDStS2ADbULw0XVhAPP+O5CgC2Eyid8yLBsnG8FbKNj8yoCrRCOu8LI9w9HRXHPrlwcMk5wk8IGsqTrzSue4ipkyG8dT83lskSWrGnOmB+wnREuJxj9ByUvv5vDBnOGmJiGb/6rkHVwBO3aKsuVQ2YJ13QZSFeQfjtLe5+67u0fxJMry3koxNOD/6RqYRyHKY9cugyxquhkiDknBxIs+jZSU2e8KlmCfLyACiF1S8KtzgCHcHJw7E4c+KEUeCX5cRjwl2Cj/NHJK6ZwykbAxnxv12LVEMxwr7/nIu79+ris2/KNSaOvqx8g+qHzVMhwNsivK5cKJsQmx9IGVwgNC5MAaXaSaLJnpBdyUhgO7UvWXcXm0xsiijrC+YwvpkJ2RrRO+Zfak+We2uZAj/KqrpPfws2OkDLl8OBmA7G2hqYguM6GDkg+rujmFI2Q1KR8OpjiiI/YJPZlHUxIA+Xk72zZWZlsp3BGdtMx8bz8xXAcPlxMUsZFtx+6q+V8mCMRvp8=
    USERNAME: AgCU3b8yA6T0aHXSzU5FvfMrMby9EcFby6JBr9CqQIzzJCsywUqfhn//NeUlH+2Pc9bA7Fa2ySTUv6XzAP1+KXLbtyTml6YoLJboc5RlhH04cRgvRIqOI2XU/e96FLosN9lHe8a6SoEperDhphPbmLktodvjHhJZCrS/Av9Jt+nO/iDjTYelqRyfuazykC6LNUTgnLji7RwJkBbAmbmbEItH9WgMxwwrxW05yP3xsJgg0VJXfdEA7a7jpQ4/djvMfXkWpNoo+gDIYX6d4CBVsRS23dwMlEDu/V6ekHA/HJT8uG7mor11jiTrcXcxY+zul1eI9wSFZe9sBFBnf3JrIEFj9uPtkk+358xuF+LxyaRLgx6YbgZQpUJP6EAryTU+5KItaIimnu1mpWDeBP8Xkm1sEqwgtZAEBH82a8iUBdlHrzVnTpWTbnapGpjis2yyS0tHK3Xe5IlSrlPp80YSEfbWtDOPHEfK4X1UmmKOumS2Tum2DlRaYhdFia7mUPjw8Yr27Hd88sllPYxetZ11ATTXgjjSyAr9N6IymptzS5N2U9V5HpruOx0ks4ykeJarCVXve44jnPZl47oi+qkGnfWdVUMfc8FJHoxxxrecmJFwEU2QiOBRsdQcXWZrx9Mv8fqLQvzv4HN+9F0icjbU3s0zd+oSqthWLmWJ/3y4irgVExw4hK6j6VCroGId7EWCNn+AhqnvpVY=
  template:
    metadata:
      creationTimestamp: null
      name: loki-credentials
      namespace: fluentbit
    type: Opaque
