flush: 10

config:
  customParsers: |
    [PARSER]
        Name        docker_utf8
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        # Magic line: decodes escaped Unicode into actual UTF-8 characters
        Decode_Field_As escaped_utf8 log

  inputs: |
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        multiline.parser docker, cri
        Parser           docker_utf8
        Tag              kube.*
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On

  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

  outputs: |
    [OUTPUT]
        Name        loki
        Match       *
        Host        logs-prod-013.grafana.net
        port        443
        tls         on
        tls.verify  on
        http_user   ${USERNAME}
        http_passwd ${PASSWORD}
        buffer_size 400k
        Labels      job=fluent-bit, namespace=$kubernetes['namespace_name'], container=$kubernetes['container_name']
        Auto_Kubernetes_Labels On

envFrom:
  - secretRef:
      name: loki-credentials
