apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://ghcr.io/dragonflydb/dragonfly/helm
