apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: flux-system

resources:
  - secrets.yaml

  - imageupdateautomation.yml

  - websocket-dc.yml
