apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: system-upgrade

resources:
  - crd.yml
  - system-upgrade-controller.yml
  - networkpolicy.yml

  - upgrade.yml
